#!/bin/bash
#The best thing in life is to run your race then wait for success at your pance,no competition in life.
#Nothing is important other than believing in Almighty Living God,He cares for us everyyday in this fucking life.wow! 
