#!bin/bash
1.its time to merge the knowledge from Agriculture  field with   the other knowledge of ICT particulary from software engineering in oder to come up with outrageous innvation that can sustain community globally
2.In anything that you do,you have to be grit over that thing them implement best move so that you  can achieve that thing.Besides, you should burn the candle to both side s so that you can  be there,yeah its possible to do that
