#!/bin/bash
#0-current_working_directory
The most  good thing in life is to run yur race since you just do things for the  success at your pance but smartly therefore I urge you guy to comply with that please
Having many wives in life is waste of money and your resources as humamn  being therefore I urge you guys to have only one wive,its good to do that much
pwd

